import React from 'react';
import {
  MapPin,
  DollarSign,
  Clock,
  Star,
  Phone,
  Mail,
  Utensils,
} from 'lucide-react';

export const PrintableItinerary = React.forwardRef(({ itinerary }, ref) => {
  if (!itinerary) return null;

  return (
    <div ref={ref} className="bg-white p-8 print:p-0">
      {/* Cover Page */}
      <div className="text-center mb-12 pb-12 border-b-4 border-blue-600">
        <div className="mb-6">
          <img
            src={itinerary.destinationImage}
            alt={itinerary.tripTitle}
            className="w-full h-64 object-cover rounded-lg shadow-lg"
            onError={(e) => {
              e.target.style.display = 'none';
            }}
          />
        </div>
        <h1 className="text-5xl font-bold text-gray-900 mb-4">
          {itinerary.tripTitle}
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          {itinerary.overview}
        </p>
        <div className="mt-6 text-sm text-gray-500">
          Generated by AI Trip Planner | {new Date().toLocaleDateString()}
        </div>
      </div>

      {/* Daily Itinerary */}
      {itinerary.dailyPlan?.map((day) => (
        <div key={day.day} className="mb-12 page-break-before">
          <h2 className="text-3xl font-bold text-blue-600 mb-6 pb-3 border-b-2 border-blue-200">
            Day {day.day}: {day.title}
          </h2>

          {/* Hotels */}
          {day.hotels && day.hotels.length > 0 && (
            <div className="mb-8">
              <h3 className="text-2xl font-bold text-gray-800 mb-4">
                🏨 Accommodation
              </h3>
              {day.hotels.map((hotel, idx) => (
                <div
                  key={idx}
                  className="mb-6 p-4 border-2 border-gray-200 rounded-lg"
                >
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <h4 className="text-xl font-bold text-gray-900">
                        {hotel.name}
                      </h4>
                      <p className="text-sm text-gray-600">
                        {hotel.type} Hotel
                      </p>
                    </div>
                    <div className="text-right">
                      <div className="flex items-center gap-1 text-blue-600 font-semibold">
                        <Star size={16} fill="currentColor" />
                        <span>{hotel.rating}</span>
                      </div>
                      <div className="text-2xl font-bold text-green-600">
                        {hotel.price}
                      </div>
                    </div>
                  </div>
                  <p className="text-sm text-gray-700 mb-3">
                    {hotel.description}
                  </p>
                  <div className="grid grid-cols-2 gap-2 text-sm">
                    <div className="flex items-center gap-1 text-gray-600">
                      <MapPin size={14} />
                      <span>{hotel.address}</span>
                    </div>
                    {hotel.contact && (
                      <>
                        <div className="flex items-center gap-1 text-gray-600">
                          <Phone size={14} />
                          <span>{hotel.contact.phone}</span>
                        </div>
                        <div className="flex items-center gap-1 text-gray-600 col-span-2">
                          <Mail size={14} />
                          <span>{hotel.contact.email}</span>
                        </div>
                      </>
                    )}
                  </div>
                  {hotel.amenities && (
                    <div className="mt-3 pt-3 border-t border-gray-200">
                      <p className="text-xs font-semibold text-gray-700 mb-1">
                        Amenities:
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {hotel.amenities.map((amenity, i) => (
                          <span
                            key={i}
                            className="text-xs bg-blue-50 text-blue-700 px-2 py-1 rounded"
                          >
                            {amenity}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}

          {/* Activities */}
          <div className="mb-8">
            <h3 className="text-2xl font-bold text-gray-800 mb-4">
              🎯 Daily Schedule
            </h3>
            <div className="space-y-4">
              {day.activities?.map((activity, idx) => (
                <div
                  key={idx}
                  className="p-4 bg-gray-50 rounded-lg border border-gray-200"
                >
                  <div className="flex items-center gap-3 mb-2">
                    <Clock size={18} className="text-blue-600" />
                    <span className="font-bold text-lg text-blue-600">
                      {activity.time}
                    </span>
                    {activity.duration && (
                      <span className="text-sm text-gray-600">
                        ({activity.duration})
                      </span>
                    )}
                  </div>
                  <h4 className="font-bold text-lg text-gray-900 mb-2">
                    {activity.type === 'meal' && (
                      <Utensils className="inline mr-2" size={18} />
                    )}
                    {activity.activity}
                  </h4>
                  <p className="text-sm text-gray-700 mb-3">
                    {activity.description}
                  </p>

                  {/* Restaurant Details */}
                  {activity.restaurant && (
                    <div className="mt-3 p-3 bg-white rounded border border-orange-200">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <h5 className="font-bold text-gray-900">
                            {activity.restaurant.name}
                          </h5>
                          <p className="text-xs text-gray-600">
                            {activity.restaurant.cuisine}
                          </p>
                        </div>
                        <span className="text-yellow-600 font-semibold text-sm">
                          ⭐ {activity.restaurant.rating}
                        </span>
                      </div>
                      <div className="grid grid-cols-2 gap-2 text-xs text-gray-600 mt-2">
                        <div>
                          <MapPin className="inline" size={12} />{' '}
                          {activity.restaurant.address}
                        </div>
                        <div>
                          <Phone className="inline" size={12} />{' '}
                          {activity.restaurant.phone}
                        </div>
                        <div>
                          <Clock className="inline" size={12} />{' '}
                          {activity.restaurant.hours}
                        </div>
                        <div>
                          <DollarSign className="inline" size={12} />{' '}
                          {activity.restaurant.priceRange}
                        </div>
                      </div>
                      {activity.restaurant.menuHighlights && (
                        <div className="mt-2">
                          <p className="text-xs font-semibold text-gray-700">
                            Menu:
                          </p>
                          <p className="text-xs text-gray-600">
                            {activity.restaurant.menuHighlights.join(', ')}
                          </p>
                        </div>
                      )}
                    </div>
                  )}

                  <div className="flex gap-4 text-sm text-gray-600 mt-3">
                    <div className="flex items-center gap-1">
                      <MapPin size={14} className="text-green-600" />
                      <span>{activity.location}</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <DollarSign size={14} className="text-green-600" />
                      <span className="font-semibold">
                        {activity.estimatedCost}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      ))}

      {/* Budget Breakdown */}
      {itinerary.budgetBreakdown && (
        <div className="mb-12 page-break-before">
          <h2 className="text-3xl font-bold text-green-600 mb-6 pb-3 border-b-2 border-green-200">
            💰 Budget Breakdown
          </h2>
          <div className="grid grid-cols-2 gap-4">
            {Object.entries(itinerary.budgetBreakdown).map(([key, value]) => (
              <div
                key={key}
                className={`flex justify-between p-4 rounded-lg ${
                  key === 'total'
                    ? 'bg-green-600 text-white font-bold text-lg col-span-2'
                    : 'bg-gray-100'
                }`}
              >
                <span className="capitalize">{key}:</span>
                <span className="font-bold">{value}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Travel Tips */}
      {itinerary.travelTips && (
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-yellow-600 mb-6 pb-3 border-b-2 border-yellow-200">
            💡 Travel Tips
          </h2>
          <ul className="space-y-3">
            {itinerary.travelTips.map((tip, idx) => (
              <li key={idx} className="flex gap-3">
                <span className="bg-yellow-600 text-white rounded-full w-7 h-7 flex items-center justify-center flex-shrink-0 font-bold text-sm">
                  {idx + 1}
                </span>
                <span className="text-gray-700">{tip}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Packing List */}
      {itinerary.packingList && (
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-purple-600 mb-6 pb-3 border-b-2 border-purple-200">
            🎒 Packing List
          </h2>
          <div className="grid grid-cols-2 gap-3">
            {itinerary.packingList.map((item, idx) => (
              <div
                key={idx}
                className="flex items-center gap-2 p-3 bg-gray-50 rounded-lg"
              >
                <span className="text-purple-600 text-lg">✓</span>
                <span className="text-gray-700">{item}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="mt-12 pt-6 border-t-2 border-gray-300 text-center text-sm text-gray-600">
        <p className="mb-2">
          Generated by <strong>AI Trip Planner</strong>
        </p>
        <p>Have an amazing trip! ✈️</p>
        <p className="mt-2 text-xs">
          All prices are estimates. Please verify details before booking.
        </p>
      </div>
    </div>
  );
});

PrintableItinerary.displayName = 'PrintableItinerary';